# [[file:../../README.org::*Origin CA Service Key][Origin CA Service Key:2]]
apiVersion: cert-manager.k8s.cloudflare.com/v1
kind: OriginIssuer
metadata:
  name: prod-issuer
  namespace: default
spec:
  requestType: OriginECC
  auth:
    serviceKeyRef:
      name: service-key
      key: key
# Origin CA Service Key:2 ends here
