name: Test
on:
  - pull_request
  - push
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  unit:
    runs-on: ubuntu-latest
    name: "Go ${{ matrix.go }} Test"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: stable
      - run: make test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "stable"
      - uses: dominikh/staticcheck-action@v1
        with:
          install-go: false
  integration:
    needs:
      - unit
      - lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "stable"
      - name: integration
        run: |
          go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
          source <(setup-envtest use -p env)
          make test
